import React from 'react'

import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Translate App',
  description: 'Generated by DNL',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body style={{ padding: '1rem' }}>
        <div className="container">{children}</div>
      </body>
    </html>
  )
}
