import React from 'react'

import type { Metadata } from 'next'

import '@styles/globals.css'

export const metadata: Metadata = {
  title: 'Translate App',
  description: 'Generated by DNL',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <body style={{ padding: '1rem' }}>{children}</body>
    </html>
  )
}
